Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -11,15 +11,27 @@ pipeline {
         stage('Checkout') {
             steps {
                sh '''
-                    ls
-                    pwd
-                    cd ..
-                    pwd
-                    ls
-                    cd Terraform@tmp
-                   terraform destroy -auto-approve \
-                  -var="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
-                  -var="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
+                        ls
+                        pwd
+                        cd ..
+                        pwd
+                        ls
+    
+                        if [ -d "Terraform@tmp" ]; then
+                            cd Terraform@tmp
+                        else
+                            echo "Error: 'Terraform@tmp' directory not found!"
+                            exit 1
+                        fi
+                        
+                        if [[ -z "$AWS_ACCESS_KEY_ID" || -z "$AWS_SECRET_ACCESS_KEY" ]]; then
+                            echo "Error: AWS credentials are not set!"
+                            exit 1
+                        fi
+                    
+                        terraform destroy -auto-approve \
+                          -var="AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
+                          -var="AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
 
                 '''
                  
